trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - infra
variables:
  - name: deploymentDefaultLocation
    value: centralus
  - name: ResourceGroupName
    value: dev-PropertyManagement
pool:
  vmImage: ubuntu-latest

jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      connectedServiceName: $(PropertyDevConnection)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: infra/main.bicep
      csmParametersFile: infra/dev.params.json
