
trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - src
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NuGetToolInstaller@1
          - task: NuGetCommand@2
            inputs:
              restoreSolution: '$(solution)'
          
          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: true
              zipAfterPublish: true
          
  - stage: Deployment
    jobs:
      - job: deploy_web_app
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureConnectionDev)'
              appType: 'webApp'
              appName: 'webapp-laohv6qoripxq'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
              deploymentMethod: 'auto'